[package]
name = "snolc-fuzz"
version = "0.0.3"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.13"
snolc = { version = "=0.0.3", path = "../crates/snolc" }

[[bin]]
name = "wire"
path = "fuzz_targets/wire.rs"
test = false
doc = false
bench = false

[[bin]]
name = "config"
path = "fuzz_targets/config.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
