[package]
name = "snolc-carrier-tcp"
description = "TCP carrier for snolc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-io.workspace = true
futures.workspace = true
libc.workspace = true
serde.workspace = true
snolc-sdk = { version = "=0.0.1", path = "../../crates/snolc-sdk" }
toml.workspace = true
