[package]
name = "snolc-cli"
description = "command line client for snolc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "snolc"
path = "src/main.rs"

[dependencies]
ctrlc.workspace = true
snolc = { version = "=0.0.1", path = "../snolc" }
snolc-ng = { version = "=0.0.1", path = "../../clients/snolcNG", default-features = false }
