pub mod acme;
pub mod carrier;
pub mod cli;
pub mod config;
pub mod error;
pub mod fragment;
pub mod frame;
pub mod handshake;
pub mod identity;
pub mod inbound;
pub mod logging;
pub mod mirror;
pub mod mux;
pub mod outbound;
pub mod protection;
pub mod routing;
pub mod runtime;
pub mod ssh;
pub mod steal;
pub mod tun;
pub mod tunnel;
pub mod webrtc;
pub mod wire_io;

pub const COMMIT_VERSION: &str = env!("SNOLC_COMMIT");
pub const WIRE_VERSION: u32 = 1;
